# Generated by Django 5.2.7 on 2025-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testimonial_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default='Your Tagline', max_length=2000),
        ),
    ]
